### ISSUE TITLE
[FEAT] Metric alerts support

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-alerting#3]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, this module only supports alerts of the type of 
- [Activity Log alerts](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-activity-log)
 
Is there any plan to support other types like metric alerts?

It would be very useful to monitor AKS clusers and issue alerts about state of pods and containers

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Potential Terraform Configuration

```hcl
n/a
```

### References

Here are some examples of AKS-specific alerts:

- https://github.com/LederWorks/terraform-azurerm-easy-alerting-aks

**Comment by Shr3ps** [comment]
Hum this module supports metrics alerts: https://github.com/claranet/terraform-azurerm-alerting/blob/master/r-metric-alerts.tf

but probably not well documented. Feel free to open a PR if you can update README & examples ;)

**Comment by mloskot** [comment]
@Shr3ps I will. Let me play with the module first :)

**Comment by HyazinthAra** [comment]
Hey, creating Metric Alerts works great using this module! 
Only thing I noticed: The outputs.tf is missing an entry for metric_alerts like the activity_log_alerts
